### ISSUE TITLE
Exercise 1 Part A (Yasmine)

### ISSUE THREAD

**Issue by bireweich** [sta426hs2024/material#3]
https://github.com/sta426hs2024/week01-getting-the-system-running-bireweich

**Comment by markrobinsonuzh** [comment]
Just noting that I see files for Exercise 3 in this repo. Note that you should have a completely independent repo for Ex. 3. I haven't looked, maybe you've done this already.

**Comment by bireweich** [comment]
Thanks for the info, I think I put the files in the right folder now.
